////////////////////////////////////////////////////////////////////////////////
//
#ifndef __MAIN_H__
#define __MAIN_H__


#ifdef __cplusplus
extern "C" {
#endif

#include "types.h"
#include "trace.h"
//#include "ucos.h"
#include "hardware.h"


extern int repeat;

int Startup(void);


#ifdef __cplusplus
}
#endif

#endif // __MAIN_H__
////////////////////////////////////////////////////////////////////////////////
