/***********************************************************************/
/*                                                                     */
/*   Module:  posixfsp.h                                               */
/*   Release: 2004.5                                                   */
/*   Version: 2003.0                                                   */
/*   Purpose: Private posixfs include directory                        */
/*                                                                     */
/*---------------------------------------------------------------------*/
/*                                                                     */
/*               Copyright 2004, Blunk Microsystems                    */
/*                      ALL RIGHTS RESERVED                            */
/*                                                                     */
/*   Licensees have the non-exclusive right to use, modify, or extract */
/*   this computer program for software development at a single site.  */
/*   This program may be resold or disseminated in executable format   */
/*   only. The source code may not be redistributed or resold.         */
/*                                                                     */
/***********************************************************************/
#ifndef _POSIXFSP_H
#define _POSIXFSP_H

#include "../include/libc/stdlib.h"
#include "../include/libc/string.h"
#include "../include/libc/errno.h"
#include "../posix.h"
#include "../include/targetos.h"
#include "../include/kernel.h"
#include "../include/sys.h"
#include "../include/fsprivate.h"

#endif /* _POSIXFSP_H */

