/***********************************************************************/
/*                                                                     */
/*   Module:  fcntl.h                                                  */
/*   Release: 2004.5                                                   */
/*   Version: 2002.0                                                   */
/*   Purpose: POSIX header file                                        */
/*                                                                     */
/*---------------------------------------------------------------------*/
/*                                                                     */
/*               Copyright 2004, Blunk Microsystems                    */
/*                      ALL RIGHTS RESERVED                            */
/*                                                                     */
/*   Licensees have the non-exclusive right to use, modify, or extract */
/*   this computer program for software development at a single site.  */
/*   This program may be resold or disseminated in executable format   */
/*   only. The source code may not be redistributed or resold.         */
/*                                                                     */
/***********************************************************************/
#ifndef _POSIX_H /* Don't include posix.h more than once */
#include "../../posix.h"
#endif

