/***********************************************************************/
/*                                                                     */
/*   Module:  shellp.h                                                 */
/*   Release: 2004.5                                                   */
/*   Version: 2000.5                                                   */
/*   Purpose: Header file for the shell application                    */
/*                                                                     */
/***********************************************************************/
#ifndef _SHELLP_H /* Don't include this file more than once */
#define _SHELLP_H

/***********************************************************************/
/* Function Prototypes                                                 */
/***********************************************************************/
void Shell(FILE *input, FILE *output);

#endif /* _SHELLP_H */

